<?php

function lm_reservation_message_hook_form_reserve_form_alter(&$form, &$form_state, $form_id)
{
    /*
     * add custom submit handler at the end of the chain , so we can check
     * if reservation was a success and fire off a notifcation
     */
    $form['#submit'][] = 'lm_reservation_message_resevation_form_submit_email';
}
function lm_reservation_message_resevation_form_submit_email(&$form, &$form_state)
{
    /*
     * check if reservation was a success and send notification email
     */
    if(isset($form_state['reserved']) && $form_state['reserved'])
    {
        //send email
    }
}

